# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Include OS Family Dependent Vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution | lower }}.yml'
    - '{{ ansible_os_family | lower }}-{{ ansible_distribution_version }}.yml'
    - '{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family | lower }}.yml'

- name: Install Singularity Dependencies
  ansible.builtin.package:
    name: '{{ singularity_dependencies }}'
    state: present

- name: Download Singularity
  ansible.builtin.get_url:
    url: '{{ singularity_url }}'
    dest: '{{ paths.build }}'
    mode: '0644'

- name: Extract Tarball
  ansible.builtin.unarchive:
    src: '{{ paths.build }}/{{ singularity_tar }}'
    dest: '{{ paths.build }}'

- name: Build and Install Singularity
  ansible.builtin.shell:
    cmd: |
      rpmbuild -tb "{{ paths.build }}/{{ singularity_tar }}" 

- name: Install Singularity RPM
  ansible.builtin.yum:
    name: "{{ singularity_rpm_path }}"
    state: present
    disable_gpg_check: yes

- name: Cleanup directory
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - '{{ paths.build }}/{{ singularity_dir }}'
    - '{{ paths.build }}/{{ singularity_tar }}'
    - "{{ ansible_env.HOME }}/rpmbuild"
