---
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# tasks file for dcgm-exporter
- name: Ensure group "prometheus" exists
  ansible.builtin.group:
    name: prometheus
    state: present
    gid: 62097

- name: Ensure user "prometheus" exists
  ansible.builtin.user:
    name: prometheus
    shell: /sbin/nologin
    comment: "a real time reporting and metrics system"
    uid: 62097
    group: prometheus

- name: Ensure directory exists
  ansible.builtin.file:
    path: '{{ paths.apps }}'
    state: directory
    mode: '0755'

- name: Install DCGM Driver
  ansible.builtin.yum:
    name: datacenter-gpu-manager
    state: present

- name: Clone DCGM exporter repo
  ansible.builtin.git:
    repo: '{{ dcgm_exporter_url }}'
    dest: '{{ dcgm_exporter_paths.src }}'
    clone: yes
    update: yes

- name: Build DCGM Exporter
  ansible.builtin.shell:
    cmd: |
      make binary
      make install
    chdir: '{{ dcgm_exporter_paths.src }}'

- name: Create dcgm-exporter config
  lineinfile:
    path: /etc/sysconfig/dcgm
    line: 'OPTIONS="--listen-address=0.0.0.0:9400"' 
    create: yes

- name: Create dcgm-exporter service
  ansible.builtin.template:
    src: dcgm-exporter.service.j2
    dest: /etc/systemd/system/dcgm-exporter.service
  notify: Handle DCGM Exporter Service

