---
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# tasks file for influxdb2
- name: Add Influxdb repos
  ansible.builtin.yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL \$releasever
    baseurl: '{{ influxdb_baseurl }}'
    enabled: yes
    gpgkey: '{{ influxdb_gpgkey }}'
    gpgcheck: yes
    state: present

- name: Ensure group "influxdb2" exists
  ansible.builtin.group:
    name: influxdb2
    state: present
    gid: 62469

- name: Ensure user "influxdb2" exists
  ansible.builtin.user:
    name: influxdb2
    shell: /sbin/nologin
    comment: "InfluxDB2 for Slurm stats"
    uid: 62469
    group: influxdb2

- name: Install influxdb2
  ansible.builtin.yum:
    name: influxdb2
    state: present

- name:  Update user in influxdb2 service file and init.sh script
  ansible.builtin.lineinfile:
    path: '{{ item }}'
    regexp: '^User=.*$'
    line: "User=influxdb2"
    backup: yes
    state: present
  loop:
    - /usr/lib/systemd/system/influxdb.service
    - /usr/lib/influxdb/scripts/init.sh

- name:  Update group in influxdb2 service file and init.sh script
  ansible.builtin.lineinfile:
    path: '{{ item }}'
    regexp: '^Group=.*$'
    line: "Group=influxdb2"
    backup: yes
    state: present
  loop:
    - /usr/lib/systemd/system/influxdb.service
    - /usr/lib/influxdb/scripts/init.sh

- name: Restart influxdb2 service
  ansible.builtin.systemd:
    name: influxdb
    daemon_reload: yes
    state: restarted
